[[redirects]]
  from = "https://guitar-shop-frontend.netlify.app/*"
  to = "https://app.guitar-shop.store/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Host = ["app.guitar-shop.store"] }
